### ISSUE TITLE
Feat: isDinero util

### ISSUE THREAD

**Issue by felixmosh** [dinerojs/dinero.js#236] opened 2021-07-15 08:36 UTC
I'm using i18next for translation & formatting prices / dates, in order to format an object, I need to check if it is a price object.

it can be really awesome if the lib will contain a utility function which will return `true` if it gets the dinero object.

WDYT?

**Comment by sarahdayan** [comment] 2021-07-15 19:24
Hey @felixmosh! The only way to check whether something is a Dinero object is to "duck type" it.

However, this isn't a silver bullet because you could have something else in your code that looks like a Dinero object but isn't one. There's no way to know in advance, only when you know the target codebase. That's why for now, I believe it's safer to keep this code userland.

I would recommend creating your own utility, something like:

```js
function isDinero(maybeDineroObject) {
  return (
    maybeDineroObject.hasOwnProperty('calculator') &&
    maybeDineroObject.hasOwnProperty('create') &&
    maybeDineroObject.hasOwnProperty('toJSON')
  );
}
```

Keep in mind that these properties are internal, so I'd also recommend writing tests so nothing breaks when you upgrade.

I'm moving this into a GitHub Discussion to keep it open, and since this is a feature request (and not a bug). If other users express the need for it, we can all chat about it over there and reconsider.

**Closed** 2021-07-15 19:25 UTC
